
LOG_NAME: test

spring:
  application:
    name: test
  main:
    banner-mode: 'off'
  liquibase:
    enabled: false
  jpa:
    properties:
      javax.persistence.schema-generation.scripts.action: create
      javax.persistence.schema-generation.scripts.create-target: target/create-embedded.sql
      javax.persistence.schema-generation.database.action: drop-and-create
      javax.persistence.schema-generation.create-source: metadata
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent-output: true
  cloud:
    kubernetes:
      enabled: false

  mvc:
    log-request-details: true

sso:
  jwt:
    internal:
      signature:
        key:
          type: VALUE
          # need exactly 256 bits
          value: '01234567890123456789012345678901'

eureka:
  client:
    enabled: false

hystrix:
  metrics:
    enabled: false

backbase:
  activemq:
    enabled: false
  security:
    mtls:
      enabled: false
