openapi: 3.0.3
info:
  title: Legal entity composition API
  version: 2.0.0
servers:
  - url: http://localhost:8080/service-api/v1
    description: The server
tags:
  - name: LegalEntityComposition
paths:
  /service-api/v2/ingest/pull:
    post:
      tags:
        - LegalEntityComposition
      summary: Ingests legal entity (in pull mode).
      description: Ingests legal entity (in pull mode).
      operationId: pullLegalEntity
      requestBody:
        description: Pull Ingestion Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegalEntityPullIngestionRequest'
      responses:
        "201":
          description: Legal Entity ingested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalEntityIngestionResponse'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /service-api/v2/ingest/push:
    post:
      tags:
        - LegalEntityComposition
      summary: Ingests legal entity (in push mode).
      description: Ingests legal entity (in push mode).
      operationId: pushLegalEntity
      requestBody:
        description: Push Ingestion Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegalEntityPushIngestionRequest'
      responses:
        "201":
          description: Legal Entity ingested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalEntityIngestionResponse'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    BadRequest:
      required:
        - message
      type: object
      properties:
        message:
          type: string

    LegalEntityPullIngestionRequest:
      type: object
      properties:
        legalEntityExternalId:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity/properties/externalId'
          description: The Legal Entity External Identifier. This is usually the pivot for the entity (a person or a company) in the Bank's core
        legalEntityInternalId:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity/properties/internalId'
          description: The Legal Entity Internal Identifier. This is usually the pivot for the entity (a person or a company) in DBS
        taxId:
          type: string
          description: The Tax ID associated with the legal entity
        userExternalId:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/User/properties/externalId'
          description: The external identifier for the user. In most cases, this will be the username
        parentLegalEntityExternalId:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity/properties/parentExternalId'
          description: The parent Legal Entity's External Identifier
        realmName:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity/properties/realmName'
          description: The Identity realm name that the legal entity belongs to.
        referenceJobRoleNames:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/JobProfileUser/properties/referenceJobRoleNames'
          description: The reference job roles that should get assigned to the user
        isAdmin:
          type: boolean
          description: Indicates if the user is an administrator on the Legal Entity
        identityUserLinkStrategy:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/IdentityUserLinkStrategy'
        productChainEnabled:
          type: boolean
          description: Flag to indicate if Product Ingestion should follow Legal Entity Ingestion
        additions:
          type: object
          additionalProperties:
            type: string

    LegalEntityPushIngestionRequest:
      type: object
      properties:
        legalEntity:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity'

    LegalEntityIngestionResponse:
      type: object
      properties:
        legalEntity:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity'
        membershipAccounts:
          type: array
          items:
            type: string

    InternalServerError:
      required:
        - message
      type: object
      properties:
        message:
          type: string




