version: "3.7"
# https://docs.docker.com/compose/compose-file/

x-common-variables: &common-variables
  SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  EXTERNAL_SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  EXTERNAL_ENC_SECRET_KEY: JWTEncKeyDontUseInProduction666!
  eureka.client.serviceUrl.defaultZone: http://host.docker.internal:8080/registry/eureka/
  eureka.instance.non-secure-port: 8080
  management.endpoints.web.exposure.include: info,health,beans,bindings,gateway
  SPRING_MAIN_BANNER-MODE: 'off'
  logging.level.root: INFO
  logging.level.com.backbase: DEBUG
  # logging.pattern.level: "%5p [%cn,%X{traceId:-},%X{spanId:-}]"


x-database-variables: &database-variables
  spring.datasource.username: root
  spring.datasource.password: root
  spring.datasource.url: jdbc:mysql://host.docker.internal:3306/user_manager?useSSL=false
  spring.datasource.driver-class-name: com.mysql.jdbc.Driver


x-message-broker-variables: &message-broker-variables
  spring.activemq.broker-url: tcp://host.docker.internal:61616
  spring.activemq.user: admin
  spring.activemq.password: admin

services:


  user-manager:
    image: repo.backbase.com/backbase-docker-releases/user-manager:2021.11
    ports:
      - "8086:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      <<: *database-variables
