server.port: 9005

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://localhost:3306/transaction_cursor?createDatabaseIfNotExist=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-persistence.xml


backbase:
  communication:
    http:
      client-secret: bb-secret
      client-id: bb-client
      access-token-uri: http://localhost:8181/oidc-token-converter-service/oauth/token
  stream:
    dbs:
      user-manager-base-url: http://localhost:8086/user-manager
      user-profile-manager-base-url: http://localhost:8086/user-profile-manager
      access-control-base-url: http://localhost:8086/access-control
      arrangement-manager-base-url: http://localhost:8082/arrangement-manager

logging:
  level:
    com.backbase.stream.compositions: DEBUG

backbase.activemq.enabled: true
spring.activemq.broker-url: tcp://localhost:61616

eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

