spring:
  application:
    name: transaction-cursor
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-persistence.xml

backbase:
  activemq:
    enabled: true
  communication:
    http:
      default-service-port: 8080
  stream:
    legalentity:
      sink:
        useIdentityIntegration: true

logging:
  level:
    com.backbase.stream.compositions: DEBUG

sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

