apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "stream-task.fullname" . }}
  labels:
{{ include "stream-task.labels" . | indent 4 }}
spec:
  template:
    spec:
      restartPolicy: {{ .Values.image.restartPolicy }}
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      containers:
        - name: stream-task-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
  backoffLimit: {{ .Values.backoffLimit}}
