openapi: 3.0.3
info:
  title: Legal Entity Integration API
  version: 2.0.0
servers:
  - url: http://localhost:8080/service-api/v2
    description: The server
tags:
  - name: LegalEntityIntegration
paths:
  /integration-api/v2/legal-entity:
    post:
      tags:
        - LegalEntityIntegration
      summary: Pulls legal entity.
      description: Pulls legal entity.
      operationId: pullLegalEntity
      requestBody:
        description: Pull Legal Entity Integration
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PullLegalEntityRequest'
      responses:
        "200":
          description: Legal Entity successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PullLegalEntityResponse'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    BadRequest:
      required:
        - message
      type: object
      properties:
        message:
          type: string

    PullLegalEntityRequest:
      type: object
      properties:
        legalEntityExternalId:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity/properties/externalId'
          description: The Legal Entity External Identifier. This is usually the pivot for the entity (a person or a company) in the Bank's core
        taxId:
          type: string
          description: The Tax ID associated with the legal entity
        userExternalId:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/User/properties/externalId'
          description: The external identifier for the user. In most cases, this will be the username
        parentLegalEntityExternalId:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity/properties/parentExternalId'
          description: The parent Legal Entity's External Identifier
        realmName:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity/properties/realmName'
          description: The Identity realm name that the legal entity belongs to.
        referenceJobRoleNames:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/JobProfileUser/properties/referenceJobRoleNames'
          description: The reference job roles that should get assigned to the user
        isAdmin:
          type: boolean
          description: Indicates if the user is an administrator on the Legal Entity
        identityUserLinkStrategy:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/IdentityUserLinkStrategy'
        additions:
          type: object
          additionalProperties:
            type: string

    PullLegalEntityResponse:
      type: object
      properties:
        legalEntity:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/LegalEntity'
        membershipAccounts:
          type: array
          items:
            type: string

    InternalServerError:
      required:
        - message
      type: object
      properties:
        message:
          type: string

