server.port: 9002

spring:
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true
backbase:
  communication:
    http:
      client-secret: bb-secret
      client-id: bb-client
      access-token-uri: http://localhost:8181/oidc-token-converter-service/oauth/token
  stream:
    dbs:
      user-manager-base-url: http://localhost:8086/user-manager
      access-control-base-url: http://localhost:8086/access-control
      arrangement-manager-base-url: http://localhost:8082/arrangement-manager
    compositions:
      product-catalog:
        enable-completed-events: false
        enable-failed-events: false
        product-catalog-integration-url: http://localhost:7002

backbase.activemq.enabled: true
spring.activemq.broker-url: tcp://localhost:61616

eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

bootstrap:
  enabled: false
  # This is just na example. Replace it with data corresponding to your project
  product-catalog:
    productKinds:
      - externalKindId: kind20
        kindName: 'Special Account'
        kinduri: 'special-account'

    productTypes:
      - externalProductId: Money Market1
        externalProductKindId: kind2
        productKindName: Current Account
        externalProductTypeId: Money Market2
        productTypeName: Money Market3
        externalId: Money Market4
        externalTypeId: Money Market5
        typeName: Money Market6
      - externalProductId: Checking
        externalProductKindId: kind3
        productKindName: Checking
        externalProductTypeId: Checking
        productTypeName: Checking
        externalId: Checking
        externalTypeId: Checking
        typeName: Checking
      - externalProductId: Savings
        externalProductKindId: kind2
        productKindName: Savings
        externalProductTypeId: Savings
        productTypeName: Savings
        externalId: Savings
        externalTypeId: Savings
        typeName: Savings

logging:
  level:
    com.backbase.stream.compositions: DEBUG
    org.mockserver: DEBUG
