server.port: 9002

spring:
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true
backbase:
  communication:
    http:
      client-secret: bb-secret
      client-id: bb-client
      access-token-uri: http://localhost:8181/oidc-token-converter-service/oauth/token
  stream:
    dbs:
      user-manager-base-url: http://localhost:8086/user-manager
      access-control-base-url: http://localhost:8086/access-control
      arrangement-manager-base-url: http://localhost:8082/arrangement-manager
    compositions:
      product-catalog:
        enable-completed-events: false
        enable-failed-events: false
        product-catalog-integration-url: http://localhost:7002

backbase.activemq.enabled: true
spring.activemq.broker-url: tcp://localhost:61616

eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

bootstrap:
  enabled: true
  # This is just na example. Replace it with data corresponding to your project
  product-catalog:

    productTypes:
      - productTypeName: Certificate of Deposit
        typeName: Certificate of Deposit
        externalProductKindId: kind6
        productKindName: Term Deposit
        externalProductId: CD
        externalId: CD
        externalProductTypeId: CD
        externalTypeId: CD
      - productTypeName: Checking Account
        typeName: Checking Account
        externalProductKindId: kind1
        productKindName: Checking Account
        externalProductId: checking-account
        externalId: checking-account
        externalProductTypeId: checking-account
        externalTypeId: checking-account
      - productTypeName: Savings Account
        typeName: Savings Account
        externalProductKindId: kind2
        productKindName: Savings Account
        externalProductId: savings-account
        externalId: savings-account
        externalProductTypeId: savings-account
        externalTypeId: savings-account
      - productTypeName: Loan
        typeName: Loan
        externalProductKindId: kind3
        productKindName: Loan Account
        externalProductId: loan-account
        externalId: loan-account
        externalProductTypeId: loan-account
        externalTypeId: loan-account

logging:
  level:
    com.backbase.stream.compositions: DEBUG
    org.mockserver: DEBUG
