openapi: 3.0.3
info:
  title: Product Integration API
  version: 2.0.0
servers:
  - url: http://localhost:8080/service-api/v1
    description: The server
tags:
  - name: ProductIntegration
paths:
  /integration-api/v2/product-group:
    post:
      tags:
        - ProductIntegration
      summary: Pulls product group.
      description: Pulls product group.
      operationId: pullProductGroup
      requestBody:
        description: Product Pull Integration Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PullProductGroupRequest'
      responses:
        "200":
          description: Product group sucessfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PullProductGroupResponse'

        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    BadRequest:
      required:
        - message
      type: object
      properties:
        message:
          type: string

    PullProductGroupRequest:
      type: object
      properties:
        legalEntityExternalId:
          type: string
        legalEntityInternalId:
          type: string
        serviceAgreementExternalId:
          type: string
        serviceAgreementInternalId:
          type: string
        userExternalId:
          type: string
        userInternalId:
          type: string
        referenceJobRoleNames:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/JobProfileUser/properties/referenceJobRoleNames'
          description: The reference job roles that should get assigned to the user
        membershipAccounts:
          type: array
          items:
            type: string
        additions:
          type: object
          additionalProperties:
            type: string

    PullProductGroupResponse:
      type: object
      properties:
        productGroup:
          $ref: '../../../../../../../api/stream-legal-entity/openapi.yaml#/components/schemas/ProductGroup'

    Product:
      type: object
      properties:
        id:
          type: string
        kind:
          type: string
        name:
          type: string

    InternalServerError:
      required:
        - message
      type: object
      properties:
        message:
          type: string
