image:
  repository: <Get access from Akshay for ECR image for retail-bootstrap-task> #853613606038.dkr.ecr.us-east-1.amazonaws.com/retail-bootstrap-task
  tag: 2022.05-0.32.0-SNAPSHOT-4
  pullPolicy: Always
  restartPolicy: OnFailure
backoffLimit: 1
resources:
  limits:
    cpu: 500m
    memory: 2048Mi
  requests:
    cpu: 125m
    memory: 256Mi
env:
  "spring.cloud.config.enabled": "false"
  "admin.basePath": <Your identity installation domain name endpoint> #https://identity-akshay.bb-se-internal.com/auth

