server.port: 7082

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

spring:
  activemq:
    broker-url: tcp://localhost:61616
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true
sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY
backbase:
  communication:
    http:
      client-secret: bb-secret
      client-id: bb-client
      access-token-uri: http://localhost:8181/oidc-token-converter-service/oauth/token
    services:
      usermanager:
        service-id: localhost:8086/user-manager
      access-control:
        service-id: localhost:8086/access-control
      arrangement:
        manager:
          service-id: localhost:8082/arrangement-manager
  mtls:
    enabled: false
  security:
    http:
      enabled: true
  stream:
    compositions:
      product:
        integration-base-url: http://localhost:7011
        chains:
          transaction-composition:
            enabled: false
            base-url: http://localhost:7083
            async: false
            excludeProductTypeExternalIds:
          payment-order-composition:
            enabled: false
            base-url: http://localhost:9005
            async: false
            excludeProductTypeExternalIds:
        events:
          enableCompleted: false
          enableFailed: false
        cursor:
          enabled: false
          base-url: http://product-cursor:8080
        ingestion-mode:
          function-groups: UPSERT
          data-groups: UPSERT
          arrangements: UPSERT
logging:
  level:
    #    root: DEBUG
    com:
      backbase:
        dbs: DEBUG
        buildingblocks: DEBUG

