server:
  port: 9003

spring:
  activemq:
    broker-url: tcp://localhost:61616
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true
sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY
eureka:
  client:
    enabled: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/

backbase:
  communication:
    services:
      usermanager:
        direct-uri: http://localhost:8060
      access-control:
        direct-uri: http://localhost:8040
      arrangement:
        manager:
          direct-uri: http://localhost:8050
    http:
      client-secret: bb-secret
      client-id: bb-client
      access-token-uri: "http://localhost:7779/oauth/token"
  stream:
    compositions:
      product:
        integration-base-url: http://localhost:7003
        chains:
          transaction-composition:
            enabled: false
            base-url: http://localhost:9004
            async: false
            excludeProductTypeExternalIds:
          payment-order-composition:
            enabled: false
            base-url: http://localhost:9004
            async: false
            excludeProductTypeExternalIds:
        events:
          enableCompleted: false
          enableFailed: true
        cursor:
          enabled: false
          base-url: http://localhost:9005

logging:
  level:
    com.backbase.stream.compositions: DEBUG
