spring:
  zipkin:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id: bb-client
            client-secret: bb-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri: http://token-converter:8080/oauth/token
  main:
    allow-bean-definition-overriding: true
sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY
backbase:
  mtls:
    enabled: false
  security:
    http:
      enabled: true
    service-api:
      authentication:
        required-scope: api:service
  stream:
    legalentity:
      sink:
        useIdentityIntegration: true
    dbs:
      user-manager-base-url: http://user-manager-nextgen:8080
      access-control-base-url: http://access-control-nextgen:8080
      arrangement-manager-base-url: http://arrangement-manage-nexgen:8080
    identity:
      identity-integration-base-url: http://identity-integration-service:8080

    compositions:
      product:
        enable-completed-events: false
        enable-failed-events: true
        product-integraion-url: http://wsecu-product-integration-service-nextgen:8080

logging:
  level:
    com.backbase.stream.compositions: DEBUG

