spring:
  application:
    name: product-composition
  main:
    allow-bean-definition-overriding: true
sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY
backbase:
  communication:
    http:
      default-service-port: 8080
  mtls:
    enabled: false
  security:
    http:
      enabled: true
  stream:
    compositions:
      product:
        chains:
          transaction-composition:
            enabled: true
            async: false
            excludeProductTypeExternalIds:
          payment-order-composition:
            enabled: true
            async: false
            excludeProductTypeExternalIds:
        events:
          enableCompleted: true
          enableFailed: true
        cursor:
          enabled: false
        ingestion-mode:
          function-groups: UPSERT
          data-groups: UPSERT
          arrangements: UPSERT
logging:
  level:
    com.backbase.dbs: DEBUG
    com.backbase.buildingblocks: DEBUG
