spring:
  zipkin:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id: bb-client
            client-secret: bb-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri: http://token-converter:8080/oauth/token
  main:
    allow-bean-definition-overriding: true
sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY
backbase:
  mtls:
    enabled: false
  security:
    http:
      enabled: true
  stream:
    dbs:
      user-manager-base-url: http://user-manager:8080
      access-control-base-url: http://access-control:8080
      arrangement-manager-base-url: http://arrangement-manager:8080
    compositions:
      product:
        integration-base-url: http://product-integration:8080
        chains:
          transaction-composition:
            enabled: true
            base-url: http://transaction-composition:8080
            async: false
            excludeProductTypeExternalIds:
          payment-order-composition:
            enabled: true
            base-url: http://localhost:9005
            async: false
            excludeProductTypeExternalIds:
        events:
          enableCompleted: true
          enableFailed: true
        cursor:
          enabled: false
          base-url: http://product-cursor:8080

logging:
  level:
    #    root: DEBUG
    com:
      backbase:
        dbs: DEBUG
        buildingblocks: DEBUG

