server:
  port: 9003

spring:
  cloud:
    loadbalancer:
      enabled: false
  activemq:
    broker-url: tcp://localhost:61616
eureka:
  instance:
    hostname: host.docker.internal
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

backbase:
  communication:
    services:
      usermanager:
        direct-uri: http://localhost:8060
      access-control:
        direct-uri: http://localhost:8040
      arrangement:
        manager:
          direct-uri: http://localhost:8050
      transaction:
        manager:
          direct-uri: http://localhost:8087
      stream:
        product:
          integration:
            direct-uri: http://localhost:7003
        transaction:
          composition:
            direct-uri: http://localhost:9004
        payment-order:
          composition:
            direct-uri: http://localhost:9004
    http:
      client-secret: bb-secret
      client-id: bb-client
      access-token-uri: "http://localhost:7779/oauth/token"
  stream:
    compositions:
      product:
        chains:
          transaction-manager:
            enabled: false
            async: false
            splitPerArrangement: false
            concurrency: 1
          transaction-composition:
            enabled: false
            async: false
            excludeProductTypeExternalIds:
          payment-order-composition:
            enabled: false
            async: false
            excludeProductTypeExternalIds:
        events:
          enableCompleted: false
          enableFailed: true
        cursor:
          enabled: false

logging:
  level:
    com.backbase: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
