openapi: 3.0.3
info:
  title: Product Catalog Composition API
  version: 2.0.0
servers:
  - url: http://localhost:8080/service-api/v1
    description: The server
tags:
  - name: ProductCatalogComposition
paths:
  /service-api/v2/pull-ingestion:
    post:
      tags:
        - ProductCatalogComposition
      summary: Ingests product catalog (in pull mode).
      description: Ingests product catalog (in pull mode).
      operationId: pullIngestProductCatalog
      responses:
        "201":
          description: Product group ingested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /service-api/v2/push-ingestion:
    post:
      tags:
        - ProductCatalogComposition
      summary: Ingests product catalog (in push mode).
      description: Ingests product catalog (in push mode).
      operationId: pushIngestProductCatalog
      requestBody:
        description: Push Ingestion Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushIngestionRequest'
      responses:
        "201":
          description: Product catalog ingested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionResponse'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    BadRequest:
      required:
        - message
      type: object
      properties:
        message:
          type: string

    PushIngestionRequest:
      type: object
      properties:
        productCatalog:
          $ref: '../../../../../../../api/stream-product-catalog/openapi.yaml#/components/schemas/ProductCatalog'

    IngestionResponse:
      type: object
      properties:
        productCatalog:
          $ref: '../../../../../../../api/stream-product-catalog/openapi.yaml#/components/schemas/ProductCatalog'

    InternalServerError:
      required:
        - message
      type: object
      properties:
        message:
          type: string

