spring:
  application:
    name: payment-order-composition
  main:
    allow-bean-definition-overriding: true
  codec:
    max-in-memory-size: 10MB
sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY

backbase:
  communication:
    http:
      default-service-port: 8080
  mtls:
    enabled: false
  security:
    http:
      enabled: true
    service-api:
      authentication:
        required-scope: api:service
  stream:
    paymentorder:
      worker:
        deletePaymentOrder: false
