server.port: 9005

spring:
  activemq:
    broker-url: tcp://localhost:61616
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  codec:
    max-in-memory-size: 10MB
  cloud:
    discovery:
      client:
        simple:
          instances:
            user-manager:
              - uri: http://localhost:8086
                metadata:
                  contextPath: /user-manager
            access-control:
              - uri: http://localhost:8086
                metadata:
                  contextPath: /access-control
            arrangement-manager:
              - uri: http://localhost:8082
                metadata:
                  contextPath: /arrangement-manager
            transaction-manager:
              - uri: http://localhost:8083
                metadata:
                  contextPath: /transaction-manager
            payment-order-service:
              - uri: http://localhost:8090
                metadata:
                  contextPath: /payment-order-service

sso.jwt.internal.signature.key:
  type: VALUE
  value: JWTSecretKeyDontUseInProduction!
backbase:
  activemq:
    enabled: true
  communication:
    http:
      client-secret: bb-secret
      client-id: bb-client
      access-token-uri: http://localhost:8181/oidc-token-converter-service/oauth/token
  stream:
    compositions:
      paymentorder:
        integration-base-url: http://localhost:7004

eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

logging:
  level:
    com.backbase.stream.compositions: DEBUG

