server.port: 9005

spring:
  activemq:
    broker-url: tcp://localhost:61616
  zipkin:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id: bb-client
            client-secret: bb-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri: http://localhost:8181/oidc-token-converter-service/oauth/token
  main:
    allow-bean-definition-overriding: true
  codec:
    max-in-memory-size: 10MB
sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY

backbase:
  mtls:
    enabled: false
  security:
    http:
      enabled: true
    service-api:
      authentication:
        required-scope: api:service
  stream:
    dbs:
      user-manager-base-url: http://user-manager:8080
      access-control-base-url: http://access-control:8080
      arrangement-manager-base-url: http://arrangement-manager:8080
      transaction-manager-base-url: http://transaction-manager:8080
      payment-order-service-base-url: http://payment-order-service:8090
    compositions:
      paymentorder:
        defaultStartOffsetInDays: 30
        integration-base-url: http://payment-order-integration:8080
        events:
          enableCompleted: true
          enableFailed: true
