# https://docs.docker.com/compose/compose-file/

x-common-variables: &common-variables
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=60.0
  SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  USERCTX_KEY: JWTSecretKeyDontUseInProduction!
  logging.level.com.backbase: DEBUG
  logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  server.shutdown: graceful
  eureka.client.serviceUrl.defaultZone: http://registry:8080/eureka
  eureka.client.healthcheck.enabled: true
  eureka.client.registry-fetch-interval-seconds: 15
  eureka.client.instance-info-replication-interval-seconds: 15
  eureka.instance.non-secure-port: 8080
  eureka.instance.initialStatus: STARTING
  backbase.activemq.enabled: false
  backbase.events.enabled: false
  backbase.audit.enabled: false
  backbase.multi-tenancy.enabled: true
  backbase.multi-tenancy.tenants[0].id: t1
  backbase.multi-tenancy.tenants[1].id: t2
  spring.main.banner-mode: off
  spring.zipkin.enabled: false
  spring.cloud.config.enabled: false

x-database-variables: &database-variables
  spring.liquibase.enabled: true
  spring.datasource.username: root
  spring.datasource.password: root
  spring.datasource.url: jdbc:mysql://mysql:3306?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  backbase.multi-tenancy.datasource.strategy: SWITCH_CATALOG

x-healthcheck-defaults: &healthcheck-defaults
  start_period: 60s
  interval: 15s
  timeout: 5s
  retries: 15

name: stream

services:
  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:rw
    healthcheck:
      test: mysqladmin ping --silent
      interval: 10s
      timeout: 5s
      retries: 5

  registry:
    image: repo.backbase.com/backbase-docker-releases/registry:${BB_VERSION}
    volumes:
      - ./utils/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java" ]

  token-converter:
    image: repo.backbase.com/backbase-docker-releases/oidc-token-converter-service:${BB_VERSION}
    environment:
      <<: *common-variables
      BACKBASE_OIDCTOKENCONVERTER_WHITELISTEDDOMAINS_0_INTERNALHOSTSCHEME: http
      BACKBASE_OIDCTOKENCONVERTER_WHITELISTEDDOMAINS_0_INTERNALHOST: identity:8080
      BACKBASE_OIDCTOKENCONVERTER_WHITELISTEDDOMAINS_0_ISSUERHOST: localhost
      BACKBASE_MULTITENANCY_TENANTFILTER_SHOULDNOTFILTERPATHS: /oauth/token,/actuator/**
    volumes:
      - ./utils/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java", "http://registry:8080/eureka/apps/token-converter", "<status>UP</status>" ]
    links:
      - registry
      - identity

  identity:
    image: repo.backbase.com/backbase-docker-releases/backbase-identity:${BB_VERSION}
    environment:
      QUARKUS_DATASOURCE_URL: "jdbc:mysql://mysql:3306/backbase_identity?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true"
      QUARKUS_DATASOURCE_USERNAME: "root"
      QUARKUS_DATASOURCE_PASSWORD: "root"
      QUARKUS_DATASOURCE_DRIVER: "com.mysql.cj.jdbc.Driver"
      QUARKUS_LOG_FILE_ENABLE: "false"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_HOME_DIR: "/"
      KEYCLOAK_CONNECTIONSJPA_QUARKUS_INITIALIZEEMPTY: "true"
      KEYCLOAK_CONNECTIONSJPA_QUARKUS_MIGRATIONSTRATEGY: "update"
      KEYCLOAK_BACKBASE_OIDC_TOKEN_CONVERTER_URL: "http://token-converter:8080"
      keycloak.backbase.providers.tenant-resolver.tenants.t1.name: "Backbase"
      keycloak.backbase.providers.tenant-resolver.tenants.t1.realms: "backbase"
      keycloak.backbase.providers.tenant-resolver.tenants.t2.name: "Moustache"
      keycloak.backbase.providers.tenant-resolver.tenants.t2.realms: "moustache"
      keycloak.hostname.default.frontendUrl: "http://localhost:8180/auth"
      JAVA_TOOL_OPTIONS: "-Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.action=import -Dkeycloak.profile.feature.upload_scripts=enabled -Dquarkus.log.category.'com.backbase'.level=DEBUG"
    volumes:
      - ./identity:/tmp/keycloak-export
      - ./utils/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java", "http://localhost:8080/auth/realms/backbase/.well-known/openid-configuration", "backbase" ]
    depends_on:
      mysql:
        condition: service_healthy

  access-control:
    image: repo.backbase.com/backbase-docker-releases/access-control:${BB_VERSION}
    environment:
      <<: [*common-variables, *database-variables]
      backbase.multi-tenancy.datasource.default-catalog: t1_access_control
      backbase.multi-tenancy.tenants[0].catalog: t1_access_control
      backbase.multi-tenancy.tenants[1].catalog: t2_access_control
    volumes:
      - ./utils/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java", "http://registry:8080/eureka/apps/access-control", "<status>UP</status>" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - registry

  user-manager:
    image: repo.backbase.com/backbase-docker-releases/user-manager:${BB_VERSION}
    environment:
      <<: [*common-variables, *database-variables]
      backbase.multi-tenancy.datasource.default-catalog: t1_user_manager
      backbase.multi-tenancy.tenants[0].catalog: t1_user_manager
      backbase.multi-tenancy.tenants[1].catalog: t2_user_manager
      BACKBASE_USERS_IDENTITYENDPOINTSENABLED: true
      BACKBASE_USERS_IDENTITYINTEGRATIONENABLED: true
      BACKBASE_USERS_SYNCPRIMARYTOIDENTITYENABLED: true
    volumes:
      - ./utils/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java", "http://registry:8080/eureka/apps/user-manager", "<status>UP</status>" ]
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - registry

  identity-integration-service:
    image: repo.backbase.com/backbase-docker-releases/identity-integration-service:${BB_VERSION}
    environment:
      <<: *common-variables
      IDENTITY_SERVERURL: http://identity:8080/auth
      IDENTITY_MASTERADMIN_USERNAME: admin
      IDENTITY_MASTERADMIN_PASSWORD: admin
      IDENTITY_REALMCONFIGURATION_FALLBACKOPTIONS_ENABLEUSER: true
      IDENTITY_REALMCONFIGURATION_FALLBACKOPTIONS_USETEMPORARYPASSWORD: true
    volumes:
      - ./utils/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java", "http://registry:8080/eureka/apps/identity-integration-service", "<status>UP</status>" ]
    links:
      - registry

  legal-entity-bootstrap-task:
    image: repo.backbase.com/backbase-stream-images/legal-entity-bootstrap-task:${STREAM_VERSION}
    environment:
      <<: *common-variables
      spring.profiles.include: moustache-bank
      bootstrap.legalEntity.realmName: moustache
      backbase.stream.client.additional-headers.x-tid: t2
    depends_on:
      token-converter:
        condition: service_healthy
      access-control:
        condition: service_healthy
      user-manager:
        condition: service_healthy
      identity-integration-service:
        condition: service_healthy
      identity:
        condition: service_healthy

  legal-entity-composition:
    image: repo.backbase.com/backbase-stream-images/legal-entity-composition-service:${STREAM_VERSION}
    ports:
      - "8989:8080"
    environment:
      <<: *common-variables
      bootstrap.enabled: true
      backbase.stream.client.additional-headers.x-tid: t1
    volumes:
      - ./utils/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "java", "/tmp/HealthCheck.java", "http://registry:8080/eureka/apps/legal-entity-composition" ]
    depends_on:
      token-converter:
        condition: service_healthy
      access-control:
        condition: service_healthy
      user-manager:
        condition: service_healthy
      identity-integration-service:
        condition: service_healthy
      identity:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: stream_default
