openapi: 3.0.3
info:
  title: Payment Order composition API
  version: 2.0.0
servers:
  - url: http://localhost:8080/service-api/v2
    description: The server
tags:
  - name: PaymentOrderComposition
paths:
  /service-api/v2/ingest/pull:
    post:
      tags:
        - PaymentOrderComposition
      summary: Ingests payment order (in pull mode).
      description: Ingests payment order (in pull mode).
      operationId: pullPaymentOrder
      requestBody:
        description: Pull Ingestion Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentOrderPullIngestionRequest'
      responses:
        "201":
          description: Payment Order ingested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentOrderIngestionResponse'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /service-api/v2/ingest/push:
    post:
      tags:
        - PaymentOrderComposition
      summary: Ingests payment order (in push mode).
      description: Ingests payment order (in push mode).
      operationId: pushIngestPaymentOrder
      requestBody:
        description: Push Ingestion Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentOrderPushIngestionRequest'
      responses:
        "201":
          description: payment order ingested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentOrderIngestionResponse'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    BadRequest:
      required:
        - message
      type: object
      properties:
        message:
          type: string

    InternalServerError:
      required:
        - message
      type: object
      properties:
        message:
          type: string

    PaymentOrderPullIngestionRequest:
      type: object
      properties:
        memberNumber:
          type: string
        internalUserId:
          type: string
        legalEntityInternalId:
          type: string
        legalEntityExternalId:
          type: string
        serviceAgreementInternalId:
          type: string
        arrangementId:
          type: string
        externalArrangementId:
          type: string
        dateRangeStart:
          type: string
          format: date-time
        dateRangeEnd:
          type: string
          format: date-time
        additions:
          type: object
          additionalProperties:
            type: string

    PaymentOrderPushIngestionRequest:
      type: object
      properties:
        paymentOrders:
          type: array
          items:
            $ref: '../../../target/yaml/payment/payment-order-service-api-v3.15.0.yaml#/components/schemas/PaymentOrderPostRequest'

    PaymentOrderIngestionResponse:
      type: object
      properties:
        newPaymentOrder:
          type: array
          items:
            $ref: '../../../target/yaml/payment/payment-order-service-api-v3.15.0.yaml#/components/schemas/PaymentOrderPostResponse'
        updatedPaymentOrder:
          type: array
          items:
            $ref: '../../../target/yaml/payment/payment-order-service-api-v3.15.0.yaml#/components/schemas/PaymentOrderPostResponse'
        deletedPaymentOrder:
          type: array
          items:
            type: string
