openapi: 3.0.3
info:
  title: Payment Order Integration API
  version: 2.0.0
servers:
  - url: http://localhost:8080/service-api/v1
    description: The server
tags:
  - name: PaymentOrderIntegration
paths:
  /service-api/v2/payment-order:
    post:
      tags:
        - PaymentOrderIntegration
      summary: Pulls Payment Orders for the Arrangement and either date range of number of billing cycles.
      description: Pulls payment orders.
      operationId: pullPaymentOrders
      requestBody:
        description: Push Ingestion Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PullIngestionRequest'

      responses:
        "200":
          description: Payment Order sucessfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PullPaymentOrderResponse'

        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'

components:
  schemas:
    BadRequest:
      required:
        - message
      type: object
      properties:
        message:
          type: string

    InternalServerError:
      required:
        - message
      type: object
      properties:
        message:
          type: string

    PullIngestionRequest:
      type: object
      properties:
        memberNumber:
          type: string
        internalUserId:
          type: string
        legalEntityInternalId:
          type: string
        legalEntityExternalId:
          type: string
        serviceAgreementInternalId:
          type: string
        arrangementId:
          type: string
        externalArrangementId:
          type: string
        dateRangeStart:
          type: string
          format: date-time
        dateRangeEnd:
          type: string
          format: date-time
        additions:
          type: object
          additionalProperties:
            type: string

    PullPaymentOrderResponse:
      type: object
      properties:
        paymentOrder:
          type: array
          items:
            $ref: '../../../target/yaml/payment/payment-order-service-api-v2.8.0.yaml#/components/schemas/PaymentOrderPostRequest'
