server.port: 9004

spring:
  zipkin:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  codec:
    max-in-memory-size: 10MB
sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY

backbase:
  communication:
    services:
      usermanager:
        service-port: 8080
      access-control:
        service-port: 8080
      arrangement:
        manager:
          service-port: 8080
      transaction:
        manager:
          service-port: 8080
  mtls:
    enabled: false
  security:
    http:
      enabled: true
    service-api:
      authentication:
        required-scope: api:service
  stream:
    compositions:
      transaction:
        defaultStartOffsetInDays: 30
        integration-base-url: http://transaction-integration:8080
        events:
          enableCompleted: true
          enableFailed: true
        cursor:
          enabled: true
          transactionIdsFilterEnabled: false
          base-url: http://transaction-cursor:8080
