server:
  port: 9004

spring:
  cloud:
    loadbalancer:
      enabled: false
  activemq:
    broker-url: tcp://localhost:61616
  zipkin:
    enabled: false

backbase:
  communication:
    services:
      usermanager:
        direct-uri: http://localhost:8060
      access-control:
        direct-uri: http://localhost:8040
      arrangement:
        manager:
          direct-uri: http://localhost:8050
      transaction:
        manager:
          direct-uri: http://localhost:8083
      stream:
        transaction:
          cursor:
            direct-uri: http://localhost:9005
          integration:
            direct-uri: http://localhost:7004
    http:
      client-secret: bb-secret
      client-id: bb-client
      access-token-uri: "http://localhost:7779/oauth/token"
  activemq:
    enabled: true
  stream:
    compositions:
      transaction:
        defaultStartOffsetInDays: 30
        events:
          enableCompleted: true
          enableFailed: true
        cursor:
          enabled: true
          transactionIdsFilterEnabled: true

eureka:
  instance:
    hostname: host.docker.internal
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.backbase.stream.compositions: DEBUG

